sudo: required
services:
  - docker

before_install:
  - docker build -t test-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true test-client npm test

after_success:
  - docker build -t rayashi/multi-client ./client
  - docker build -t rayashi/multi-nginx ./nginx
  - docker build -t rayashi/multi-server ./server
  - docker build -t rayashi/multi-worker ./worker
  
  # Lod in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push rayashi/multi-client
  - docker push rayashi/multi-nginx
  - docker push rayashi/multi-server
  - docker push rayashi/multi-worker
